package PrimerParcial;
import Clases.Credencial;
import Clases.Libro;
import Clases.ListaCredenciales;
import Clases.consultas;
import Clases.ListaLibros;
import com.mysql.jdbc.Connection;
import java.awt.Container;
import java.awt.Point;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javafx.beans.value.ChangeListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.dbutils.DbUtils;




public class ProyectoBiblioteca extends javax.swing.JFrame {
     private String tablaActual;
    //Variable global
    consultas con = new consultas();
    public ProyectoBiblioteca() {
        initComponents();
        
         this.setResizable(false);
    
        establecerTablaActual("libros");
        cargarcombo(jcmblibro);
        cargarcombo2(jcmbcredencial);
        this.setLocationRelativeTo(this);
    ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/a .png"));

this.setIconImage(icono.getImage());

        con.RellenaLaTablaConDatosMySQL("libro", jTable_libros);
        con.leerLectores("usuario", jTable_lectores);
      
        con.leerReportes("libro", jTable_prestamos, lblmostrar);
        


       
        
        
        
        ////mostrar los datos seleccionados en los campos 
        jTable_libros.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent Mouse_evt)
                {
                    JTable table = (JTable) Mouse_evt.getSource();
                    Point point = Mouse_evt.getPoint();
                    int row = table.rowAtPoint(point);
                    if(Mouse_evt.getClickCount() == 1)
               
                {
                    jTxtTitulo.setText(jTable_libros.getValueAt(jTable_libros.getSelectedRow(), 1).toString());
                    txtautor.setText(jTable_libros.getValueAt(jTable_libros.getSelectedRow(), 2).toString());
                    jTxtEditorial.setText(jTable_libros.getValueAt(jTable_libros.getSelectedRow(), 3).toString());
                    txtcantidad.setText(jTable_libros.getValueAt(jTable_libros.getSelectedRow(), 4).toString());
                    jTxtAnio.setText(jTable_libros.getValueAt(jTable_libros.getSelectedRow(), 5).toString());
                    
                    
                }
                }
        });
        ///mostrar valores en los campos
     jTable_lectores.addMouseListener(new MouseAdapter() {
    public void mousePressed(MouseEvent Mouse_evt) {
        JTable table = (JTable) Mouse_evt.getSource();
        Point point = Mouse_evt.getPoint();
        int row = table.rowAtPoint(point);
        if (Mouse_evt.getClickCount() == 1) {
            jTxtNombre.setText(jTable_lectores.getValueAt(row, 1).toString());
            txtgrupo.setText(jTable_lectores.getValueAt(row, 2).toString());
            String libroSeleccionado = jTable_lectores.getValueAt(row, 3).toString();
            String credencialSeleccionada = jTable_lectores.getValueAt(row, 4).toString();
            jTxtTelefono.setText(jTable_lectores.getValueAt(row, 5).toString());
            jTxtCorreo.setText(jTable_lectores.getValueAt(row, 6).toString());

            // Establecer el libro seleccionado en el JComboBox
            jcmblibro.setSelectedItem(libroSeleccionado);

            // Establecer la credencial seleccionada en el JComboBox
            jcmbcredencial.setSelectedItem(credencialSeleccionada);
        }
    }
});


 

   
         
    }/////constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTbdFormulas = new javax.swing.JTabbedPane();
        jPnlFormulaGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFrtLiteralB = new javax.swing.JFormattedTextField();
        jFrtLiteralC = new javax.swing.JFormattedTextField();
        jFrtLiteralA = new javax.swing.JFormattedTextField();
        jLblLiteralA = new javax.swing.JLabel();
        jLblLiteralB = new javax.swing.JLabel();
        jLblLiteralC = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        jLblX1 = new javax.swing.JLabel();
        jLblX2 = new javax.swing.JLabel();
        jPnlMiFormula = new javax.swing.JPanel();
        Jbtn_guardar2 = new java.awt.Button();
        jTxtTitulo2 = new java.awt.TextField();
        jTxtNombre2 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_libros = new javax.swing.JTable();
        jPanel_prop = new javax.swing.JPanel();
        jLbl_titulo = new java.awt.Label();
        jLbl_editorial = new java.awt.Label();
        jLbl_anio = new java.awt.Label();
        JlblDatos = new java.awt.Label();
        jTxtAnio = new javax.swing.JTextField();
        jTxtTitulo = new javax.swing.JTextField();
        lblautor = new javax.swing.JLabel();
        txtautor = new javax.swing.JTextField();
        lblcantidad = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jTxtEditorial = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_lectores = new javax.swing.JTable();
        jPanelDatosUsuario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jLblTelefono = new javax.swing.JLabel();
        jLblCorreo = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jTxtTelefono = new javax.swing.JTextField();
        jTxtCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtgrupo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcmbcredencial = new javax.swing.JComboBox<>();
        jcmblibro = new javax.swing.JComboBox<>();
        btnnuevo = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_prestamos = new javax.swing.JTable();
        label1 = new java.awt.Label();
        jPanel_buttons = new javax.swing.JPanel();
        Jbtn_actualizar = new javax.swing.JButton();
        Jbtn_guardar = new javax.swing.JButton();
        Jbtn_eliminar = new javax.swing.JButton();
        Jbtn_nuevo = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        lblmostrar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPnlFormulaGeneral.setBackground(new java.awt.Color(255, 204, 0));
        jPnlFormulaGeneral.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Ingresa la literales y resuelve la fórmula");

        jFrtLiteralB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFrtLiteralB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFrtLiteralBActionPerformed(evt);
            }
        });

        jFrtLiteralC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFrtLiteralC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFrtLiteralCActionPerformed(evt);
            }
        });

        jFrtLiteralA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFrtLiteralA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFrtLiteralAActionPerformed(evt);
            }
        });

        jLblLiteralA.setText("a:");

        jLblLiteralB.setText("b:");

        jLblLiteralC.setText("c:");

        Separator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLblX1.setText("X1:");

        jLblX2.setText("x2:");

        javax.swing.GroupLayout jPnlFormulaGeneralLayout = new javax.swing.GroupLayout(jPnlFormulaGeneral);
        jPnlFormulaGeneral.setLayout(jPnlFormulaGeneralLayout);
        jPnlFormulaGeneralLayout.setHorizontalGroup(
            jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlFormulaGeneralLayout.createSequentialGroup()
                .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlFormulaGeneralLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1))
                    .addGroup(jPnlFormulaGeneralLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblLiteralA)
                            .addComponent(jLblLiteralB)
                            .addComponent(jLblLiteralC))
                        .addGap(27, 27, 27)
                        .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFrtLiteralA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFrtLiteralC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFrtLiteralB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblX1)
                            .addComponent(jLblX2))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPnlFormulaGeneralLayout.setVerticalGroup(
            jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlFormulaGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlFormulaGeneralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlFormulaGeneralLayout.createSequentialGroup()
                                .addGap(0, 14, Short.MAX_VALUE)
                                .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFrtLiteralA, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblLiteralA))
                                .addGap(18, 18, 18)
                                .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFrtLiteralB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblLiteralB))
                                .addGap(18, 18, 18)
                                .addGroup(jPnlFormulaGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jFrtLiteralC, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblLiteralC)))
                            .addComponent(Separator))
                        .addGap(19, 19, 19))
                    .addGroup(jPnlFormulaGeneralLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLblX1)
                        .addGap(52, 52, 52)
                        .addComponent(jLblX2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTbdFormulas.addTab("Fórmula General", jPnlFormulaGeneral);

        javax.swing.GroupLayout jPnlMiFormulaLayout = new javax.swing.GroupLayout(jPnlMiFormula);
        jPnlMiFormula.setLayout(jPnlMiFormulaLayout);
        jPnlMiFormulaLayout.setHorizontalGroup(
            jPnlMiFormulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        jPnlMiFormulaLayout.setVerticalGroup(
            jPnlMiFormulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        jTbdFormulas.addTab("Mi Fórmula", jPnlMiFormula);

        Jbtn_guardar2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        Jbtn_guardar2.setLabel("Guardar");

        jTxtTitulo2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTxtNombre2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca CECyTES Pesqueira");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPaneStateChanged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable_libros.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable_libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_libros.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_libros.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jScrollPane1.setViewportView(jTable_libros);

        jPanel_prop.setBackground(new java.awt.Color(102, 255, 204));

        jLbl_titulo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLbl_titulo.setText("Titulo");

        jLbl_editorial.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLbl_editorial.setText("Editorial");

        jLbl_anio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLbl_anio.setText("Año");

        JlblDatos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        JlblDatos.setText("Datos para libro");

        jTxtAnio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTxtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAnioActionPerformed(evt);
            }
        });
        jTxtAnio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtAnioKeyTyped(evt);
            }
        });

        jTxtTitulo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTxtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTituloActionPerformed(evt);
            }
        });
        jTxtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtTituloKeyTyped(evt);
            }
        });

        lblautor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblautor.setText("Autor");

        txtautor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtautorFocusLost(evt);
            }
        });
        txtautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtautorActionPerformed(evt);
            }
        });
        txtautor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtautorKeyTyped(evt);
            }
        });

        lblcantidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblcantidad.setText("Cantidad");

        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });

        jTxtEditorial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTxtEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEditorialActionPerformed(evt);
            }
        });
        jTxtEditorial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtEditorialKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel_propLayout = new javax.swing.GroupLayout(jPanel_prop);
        jPanel_prop.setLayout(jPanel_propLayout);
        jPanel_propLayout.setHorizontalGroup(
            jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_propLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_propLayout.createSequentialGroup()
                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcantidad)
                            .addComponent(jLbl_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtAnio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JlblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_propLayout.createSequentialGroup()
                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblautor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtEditorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtautor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel_propLayout.setVerticalGroup(
            jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_propLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(JlblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtautor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblautor))
                .addGap(29, 29, 29)
                .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLbl_editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel_propLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLbl_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_prop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel_prop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Libros", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(35000, 39000));

        jTable_lectores.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTable_lectores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_lectores.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_lectores.setSelectionBackground(new java.awt.Color(0, 153, 255));
        jTable_lectores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_lectoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_lectores);

        jPanelDatosUsuario.setBackground(new java.awt.Color(102, 255, 204));
        jPanelDatosUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Datos para usuario");

        jLblNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblNombre.setText("Nombre");

        jLblTelefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblTelefono.setText("Telefono");

        jLblCorreo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLblCorreo.setText("Correo");

        jTxtNombre.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTxtNombre.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTxtNombreInputMethodTextChanged(evt);
            }
        });
        jTxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNombreKeyTyped(evt);
            }
        });

        jTxtTelefono.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtTelefonoKeyTyped(evt);
            }
        });

        jTxtCorreo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Grupo");

        txtgrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgrupoActionPerformed(evt);
            }
        });
        txtgrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgrupoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Libro");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Credencial");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jcmbcredencial, org.jdesktop.beansbinding.ObjectProperty.create(), jcmbcredencial, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jcmbcredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbcredencialActionPerformed(evt);
            }
        });

        btnnuevo.setBackground(new java.awt.Color(255, 102, 0));
        btnnuevo.setText("Libro Nuevo ");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosUsuarioLayout = new javax.swing.GroupLayout(jPanelDatosUsuario);
        jPanelDatosUsuario.setLayout(jPanelDatosUsuarioLayout);
        jPanelDatosUsuarioLayout.setHorizontalGroup(
            jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                        .addComponent(jLblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtNombre))
                    .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                        .addComponent(jLblCorreo)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtCorreo))
                    .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(txtgrupo))
                    .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                        .addComponent(jLblTelefono)
                        .addGap(10, 10, 10)
                        .addComponent(jTxtTelefono))
                    .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmbcredencial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(jcmblibro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 189, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnuevo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosUsuarioLayout.setVerticalGroup(
            jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNombre)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4))
                    .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcmblibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcmbcredencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTelefono)
                    .addComponent(jTxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnnuevo)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanelDatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Prestamos", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTable_prestamos.setAutoCreateRowSorter(true);
        jTable_prestamos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable_prestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_prestamos.setGridColor(new java.awt.Color(255, 255, 255));
        jTable_prestamos.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jScrollPane3.setViewportView(jTable_prestamos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Conteo de Libros", jPanel4);

        label1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 153, 51));
        label1.setText("Administracion");

        jPanel_buttons.setBackground(new java.awt.Color(255, 255, 255));

        Jbtn_actualizar.setBackground(new java.awt.Color(255, 102, 0));
        Jbtn_actualizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Jbtn_actualizar.setText("Actualizar");
        Jbtn_actualizar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Jbtn_actualizarStateChanged(evt);
            }
        });
        Jbtn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_actualizarActionPerformed(evt);
            }
        });

        Jbtn_guardar.setBackground(new java.awt.Color(0, 255, 0));
        Jbtn_guardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Jbtn_guardar.setText("Guardar");
        Jbtn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_guardarActionPerformed(evt);
            }
        });

        Jbtn_eliminar.setBackground(new java.awt.Color(255, 0, 51));
        Jbtn_eliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Jbtn_eliminar.setText("Eliminar");
        Jbtn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_eliminarActionPerformed(evt);
            }
        });

        Jbtn_nuevo.setBackground(new java.awt.Color(51, 255, 51));
        Jbtn_nuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Jbtn_nuevo.setText("Limpiar campos");
        Jbtn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_nuevoActionPerformed(evt);
            }
        });

        txtbuscar.setText("Buscar:");
        txtbuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtbuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbuscarFocusLost(evt);
            }
        });
        txtbuscar.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtbuscarCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel_buttonsLayout = new javax.swing.GroupLayout(jPanel_buttons);
        jPanel_buttons.setLayout(jPanel_buttonsLayout);
        jPanel_buttonsLayout.setHorizontalGroup(
            jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jbtn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Jbtn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(Jbtn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel_buttonsLayout.setVerticalGroup(
            jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Jbtn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Jbtn_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addComponent(Jbtn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel_buttonsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jbtn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        lblmostrar.setText("Cantidad de libros: ");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Derechos Reservados: DEVFELIX.R.G");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblmostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void jFrtLiteralBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFrtLiteralBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrtLiteralBActionPerformed

    private void jFrtLiteralCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFrtLiteralCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrtLiteralCActionPerformed

    private void jFrtLiteralAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFrtLiteralAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrtLiteralAActionPerformed

    private void Jbtn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_guardarActionPerformed
     
     int indexSelect = jTabbedPane.getSelectedIndex();
switch(indexSelect) {
    case 0: // Pestaña de libros
        // Obtener los datos del nuevo libro de los campos de texto
        String titulo = jTxtTitulo.getText();
        String autor = txtautor.getText();
        String editorial = jTxtEditorial.getText();
        String cantidad = txtcantidad.getText();
        String anio = jTxtAnio.getText();

        // Verificar si alguno de los campos está vacío antes de insertar el libro
        if (titulo.isEmpty() || autor.isEmpty() || editorial.isEmpty() || cantidad.isEmpty() || anio.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos para agregar un nuevo libro.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
        } else if (anio.length() != 4 || !anio.matches("\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un año válido de cuatro dígitos.", "Año Inválido", JOptionPane.WARNING_MESSAGE);
        } else {
            // Verificar si el libro ya existe en la base de datos
            if (con.existeLibro(titulo)) {
                JOptionPane.showMessageDialog(this, "El libro '" + titulo + "' ya existe en la base de datos.", "Libro Existente", JOptionPane.WARNING_MESSAGE);
            } else {
                // Insertar el nuevo libro en la base de datos
                con.InsertarLibro(jTxtTitulo, txtautor, jTxtEditorial, txtcantidad, jTxtAnio);

                // Actualizar la tabla de libros
                con.RellenaLaTablaConDatosMySQL("libro", jTable_libros);
                cargarcombo(jcmblibro);
                // Esta es la llamada al conteo
                
                // Mostrar mensaje de éxito
                JOptionPane.showMessageDialog(this, "Nuevo libro agregado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                // Limpiar los campos de texto
                jTxtTitulo.setText("");
                txtautor.setText("");
                jTxtEditorial.setText("");
                txtcantidad.setText("");
                jTxtAnio.setText("");
            }
        }
        break;
        case 1:
    // Obtener los datos del nuevo usuario de los campos de texto y del JComboBox
    String nombre = jTxtNombre.getText();
    String grupo = txtgrupo.getText();
    String telefono = jTxtTelefono.getText();
    String correo = jTxtCorreo.getText();
    String libroSeleccionado = (String) jcmblibro.getSelectedItem();
    String credencialSeleccionada = (String) jcmbcredencial.getSelectedItem();

    // Verificar si alguno de los campos está vacío antes de insertar el usuario
    if (nombre.isEmpty() || grupo.isEmpty() || telefono.isEmpty() || correo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos para agregar un nuevo usuario.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
    } else if (telefono.length() != 10 || !telefono.matches("\\d{10}")) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un número de teléfono válido de 10 dígitos.", "Número de Teléfono Inválido", JOptionPane.WARNING_MESSAGE);
    } else {
        // Insertar el nuevo usuario en la base de datos
        con.InsertarUsuario(jTxtNombre, txtgrupo, libroSeleccionado, credencialSeleccionada, jTxtTelefono, jTxtCorreo);

        // Actualizar la tabla de usuarios
        con.leerLectores("usuario", jTable_lectores);

        // Mostrar mensaje de éxito
        // Lamada al conteo
        JOptionPane.showMessageDialog(this, "Nuevo prestamo agregado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Limpiar los campos de texto
        jTxtNombre.setText("");
        txtgrupo.setText("");
        jTxtTelefono.setText("");
        jTxtCorreo.setText("");
    }
    break;

    }
    
        

    }//GEN-LAST:event_Jbtn_guardarActionPerformed

    private void Jbtn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_actualizarActionPerformed
        // TODO add your handling code here:
        int indexSelect = jTabbedPane.getSelectedIndex();
switch(indexSelect) {
    case 0:
        // Obtener el ID del libro seleccionado
        int selectedRowLibros = jTable_libros.getSelectedRow();
        if (selectedRowLibros != -1) {
            String idLibro = jTable_libros.getValueAt(selectedRowLibros, 0).toString();

            // Obtener los datos del libro de los campos de texto
            String tituloLibro = jTxtTitulo.getText();
            String autorLibro = txtautor.getText();
            String editorialLibro = jTxtEditorial.getText();
            String cantidadLibroStr = txtcantidad.getText();
            String anioLibro = jTxtAnio.getText();

            // Verificar si alguno de los campos está vacío
            if (tituloLibro.isEmpty() || autorLibro.isEmpty() || editorialLibro.isEmpty() || cantidadLibroStr.isEmpty() || anioLibro.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos para actualizar el libro.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
                return; // Salir del método si hay campos vacíos
            }

            // Validar que el campo 'cantidad' sea un entero válido
            int cantidadLibro;
            try {
                cantidadLibro = Integer.parseInt(cantidadLibroStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido para la cantidad.", "Cantidad no válida", JOptionPane.WARNING_MESSAGE);
                return; // Salir del método si 'cantidad' no es un entero válido
            }

            // Realizar la actualización del libro en la base de datos
            con.ActualizarLibro(jTxtTitulo, txtautor, jTxtEditorial, txtcantidad, jTxtAnio, idLibro);
            con.RellenaLaTablaConDatosMySQL("libro", jTable_libros);
            ///esta es la llamada al conteo
           
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un libro.", "Campo no seleccionado", JOptionPane.WARNING_MESSAGE);
        }
        break;
    case 1:
        // Obtener el ID del usuario seleccionado
        int selectedRowLectores = jTable_lectores.getSelectedRow();
        if (selectedRowLectores != -1) {
            String idUsuario = jTable_lectores.getValueAt(selectedRowLectores, 0).toString();

            // Obtener los datos del usuario de los campos de texto y del JComboBox
            String nombreUsuario = jTxtNombre.getText();
            String grupoUsuario = txtgrupo.getText();
            String telefonoUsuario = jTxtTelefono.getText();
            String correoUsuario = jTxtCorreo.getText();
            String libroSeleccionado = (String) jcmblibro.getSelectedItem();
            String credencialSeleccionada = (String) jcmbcredencial.getSelectedItem();

            // Verificar si alguno de los campos está vacío
            if (nombreUsuario.isEmpty() || grupoUsuario.isEmpty() || telefonoUsuario.isEmpty() || correoUsuario.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos para actualizar el usuario.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
                return; // Salir del método si hay campos vacíos
            }

            // Realizar la actualización del usuario en la base de datos
            con.ActualizarUsuario(jTxtNombre, txtgrupo, libroSeleccionado, credencialSeleccionada, jTxtTelefono, jTxtCorreo, idUsuario);
            con.leerLectores("usuario", jTable_lectores);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un usuario.", "Campo no seleccionado", JOptionPane.WARNING_MESSAGE);
        }
        break;
    default:
        break;
}

    }//GEN-LAST:event_Jbtn_actualizarActionPerformed

    private void Jbtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_eliminarActionPerformed
        // TODO add your handling code here:
       int indexSelect = jTabbedPane.getSelectedIndex();
    
    // Verificar si se ha seleccionado algún campo en la tabla
    if (indexSelect == 0 && jTable_libros.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un libro a eliminar.", "Campo no seleccionado", JOptionPane.WARNING_MESSAGE);
        return; // Salir del método si no se ha seleccionado ningún libro
    } else if (indexSelect == 1 && jTable_lectores.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un usuario a eliminar.", "Campo no seleccionado", JOptionPane.WARNING_MESSAGE);
        return; // Salir del método si no se ha seleccionado ningún usuario
    }

    // Si se ha seleccionado un campo, proceder con la eliminación
    switch(indexSelect){
        case 0:
            String id = jTable_libros.getValueAt(jTable_libros.getSelectedRow(), 0).toString();
            con.EliminaRegistro("id_libro", "libro", id);
            con.RellenaLaTablaConDatosMySQL("libro", jTable_libros);
            ///esta es la llamada al conteo
             
            break;
        case 1:
            String idUsuario = jTable_lectores.getValueAt(jTable_lectores.getSelectedRow(), 0).toString();
            con.EliminaRegistro("id_usuario", "usuario", idUsuario);
            con.leerLectores("usuario", jTable_lectores);
            break;
        default:
            break;
    }
    }//GEN-LAST:event_Jbtn_eliminarActionPerformed

    private void Jbtn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_nuevoActionPerformed
        // TODO add your handling code here:
        txtautor.setText("");
        jTxtEditorial.setText("");
        jTxtAnio.setText("");
        jTxtNombre.setText("");
        txtcantidad.setText("");
        jTxtTelefono.setText("");
        jTxtTitulo.setText("");
        jTxtCorreo.setText("");
       
        txtgrupo.setText("");
        
    }//GEN-LAST:event_Jbtn_nuevoActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyPressed
private void establecerTablaActual(String tabla) {
    tablaActual = tabla;
    System.out.println("Tabla actual: " + tablaActual);
}

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        // TODO add your handling code here:
     String textoBuscar = txtbuscar.getText();
    
   if (tablaActual.equals("libros")) {
    consultas consultaLibros = new consultas();
    DefaultTableModel modelo = consultaLibros.buscarElemento(textoBuscar);
    jTable_libros.setModel(modelo);
} else if (tablaActual.equals("usuarios")) {
    consultas consultaUsuarios = new consultas();
    DefaultTableModel modelo = consultaUsuarios.buscarElementoUsuario(textoBuscar);
    jTable_lectores.setModel(modelo);
}
       
        
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void jTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPaneStateChanged
        // TODO add your handling code here:
        int selectedIndex = jTabbedPane.getSelectedIndex();
    
    // Verifica la pestaña actual y establece la tabla actual correspondiente
    if (selectedIndex == 0) { // Si la primera pestaña (libros) está activa
        establecerTablaActual("libros");
    } else if (selectedIndex == 1) { // Si la segunda pestaña (lectores) está activa
        establecerTablaActual("usuarios");
    } else if (selectedIndex == 2) { // Si la tercera pestaña (reportes) está activa
        establecerTablaActual("reportes");
        
    }
    
    // Muestra u oculta el JLabel según la pestaña actual
    if (selectedIndex == 2) { // Si está en la pestaña de Reportes
        lblmostrar.setVisible(true);
        
    } else {
        lblmostrar.setVisible(false);
        
    }
    }//GEN-LAST:event_jTabbedPaneStateChanged

    private void jcmbcredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbcredencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbcredencialActionPerformed

    private void txtgrupoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgrupoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        // Verificar si el carácter es un número o una letra y si la longitud actual es menor que 2
        if (!(Character.isDigit(c) && txtgrupo.getText().length() < 1) && !(Character.isLetter(c) && txtgrupo.getText().length() == 1)) {
            // Si no es un número o una letra después de un número, consumir el evento
            evt.consume();
        }
    }//GEN-LAST:event_txtgrupoKeyTyped

    private void txtgrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgrupoActionPerformed

    private void jTxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTelefonoKeyTyped
        // TODO add your handling code here:
        ///campos de numeros
        char c = evt.getKeyChar();
        // Verificar si el carácter es un dígito
        if (!(Character.isDigit(c) && jTxtTelefono.getText().length() < 10)) {

            evt.consume();
        }
    }//GEN-LAST:event_jTxtTelefonoKeyTyped

    private void jTxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNombreKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
    String text = jTxtNombre.getText();

    // Verificar si el carácter es una letra (mayúscula o minúscula) o un espacio
    if (!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == ' ')) {
        // Si no es una letra ni un espacio, consumir el evento para evitar que se ingrese
        evt.consume();
        return;
    }

    // Si el carácter es una letra y es el primer carácter o sigue a un espacio, convertir a mayúscula
    if (c != ' ' && (text.isEmpty() || text.charAt(text.length() - 1) == ' ')) {
        c = Character.toUpperCase(c);
    } else if (c != ' ') {
        // Convertir las demás letras a minúscula si es necesario
        c = Character.toLowerCase(c);
    }

    // Insertar el carácter modificado en el campo de texto
    jTxtNombre.setText(text + c);
    
    // Consumir el evento original para evitar la entrada duplicada
    evt.consume();
    }//GEN-LAST:event_jTxtNombreKeyTyped

    private void jTxtNombreInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTxtNombreInputMethodTextChanged
        // TODO add your handling code here:

        ///
    }//GEN-LAST:event_jTxtNombreInputMethodTextChanged

    private void jTable_lectoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_lectoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_lectoresMouseClicked

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
        // TODO add your handling code here:
      char c = evt.getKeyChar();
    String currentText = txtcantidad.getText();
    
    // Verificar si el carácter es un dígito
    if (!Character.isDigit(c)) {
        evt.consume();
        return;
    }

    // Si es el primer carácter y es un cero, no permitirlo
    if (currentText.isEmpty() && c == '0') {
        evt.consume();
        return;
    }

    // Si la longitud actual es mayor o igual a 3, no permitir más caracteres
    if (currentText.length() >= 3) {
        evt.consume();
        return;
    }
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void txtautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtautorActionPerformed
        // TODO add your handling code here:
        // Obtén el contenido actual del JTextField
    
    }//GEN-LAST:event_txtautorActionPerformed

    private void jTxtTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTituloKeyTyped
        // TODO add your handling code here:
        // Obtén el contenido actual del JTextField
    String currentText = jTxtTitulo.getText();
    
    // Verifica si el JTextField está vacío y si la tecla presionada es una letra
    if (currentText.length() == 0 && Character.isLetter(evt.getKeyChar())) {
        // Convierte la letra a mayúscula
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }
    }//GEN-LAST:event_jTxtTituloKeyTyped

    private void jTxtAnioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtAnioKeyTyped
        // TODO add your handling code here:
      char c = evt.getKeyChar();

    // Verificar si el carácter es un dígito y si la longitud actual es menor que 4
    if (!Character.isDigit(c) || jTxtAnio.getText().length() >= 4) {
        // Si no es un dígito o si ya hay 4 caracteres, consumir el evento
        evt.consume();
        return;
    }

    // Validar el año en tiempo real
    String anio = jTxtAnio.getText() + c;
    if (anio.length() == 4) {
        try {
            int anioInt = Integer.parseInt(anio);
            // Obtener el año actual
            int anioActual = java.time.Year.now().getValue();
            // Validar que el año esté dentro del rango permitido (1800 - año actual)
            if (anioInt < 1800 || anioInt > anioActual) {
                // Si el año no es válido, mostrar un cuadro de diálogo de error y borrar el campo
                JOptionPane.showMessageDialog(null, "Año inválido", "Error", JOptionPane.ERROR_MESSAGE);
                jTxtAnio.setText("");
                evt.consume();
            }
        } catch (NumberFormatException e) {
            // Si ocurre una excepción al convertir a entero, el año no es válido
            JOptionPane.showMessageDialog(null, "Año inválido", "Error", JOptionPane.ERROR_MESSAGE);
            jTxtAnio.setText("");
            evt.consume();
        }
    }
    }//GEN-LAST:event_jTxtAnioKeyTyped

    private void txtbuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbuscarFocusGained
        // TODO add your handling code here:
         if (txtbuscar.getText().equals("Buscar:")) {
        txtbuscar.setText(""); // Borra el texto de búsqueda si es "Buscar:"
    }
    }//GEN-LAST:event_txtbuscarFocusGained

    private void txtbuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbuscarFocusLost
        // TODO add your handling code here:
         if (txtbuscar.getText().isEmpty()) {
        txtbuscar.setText("Buscar:"); // Restaura el texto "Buscar:" si el campo de texto está vacío
    }
    }//GEN-LAST:event_txtbuscarFocusLost

    private void txtautorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtautorKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

    // Obtén el contenido actual del JTextField
    String currentText = txtautor.getText();
    
    // Verifica si el JTextField está vacío y si la tecla presionada es una letra
    if (currentText.length() == 0 && Character.isLetter(c)) {
        // Convierte la letra a mayúscula
        evt.setKeyChar(Character.toUpperCase(c));
    }

    // Verificar si el carácter es una letra (mayúscula o minúscula) o un espacio
    if (!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == ' ')) {
        // Si no es una letra ni un espacio, consumir el evento para evitar que se ingrese
        evt.consume();
    }
    }//GEN-LAST:event_txtautorKeyTyped

    private void txtautorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtautorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtautorFocusLost

    private void txtbuscarCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtbuscarCaretPositionChanged
        // TODO add your handling code here:
                                                    


    }//GEN-LAST:event_txtbuscarCaretPositionChanged

    private void jTxtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTituloActionPerformed

    private void jTxtEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEditorialActionPerformed

    private void jTxtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAnioActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
      jTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void jTxtEditorialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtEditorialKeyTyped
        // TODO add your handling code here:
         String currentText = jTxtEditorial.getText();
    
    // Verifica si el JTextField está vacío y si la tecla presionada es una letra
    if (currentText.length() == 0 && Character.isLetter(evt.getKeyChar())) {
        // Convierte la letra a mayúscula
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }
    }//GEN-LAST:event_jTxtEditorialKeyTyped


    private void Jbtn_actualizarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Jbtn_actualizarStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_actualizarStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoBiblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_actualizar;
    private javax.swing.JButton Jbtn_eliminar;
    private javax.swing.JButton Jbtn_guardar;
    private java.awt.Button Jbtn_guardar2;
    private javax.swing.JButton Jbtn_nuevo;
    private java.awt.Label JlblDatos;
    private javax.swing.JSeparator Separator;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JFormattedTextField jFrtLiteralA;
    private javax.swing.JFormattedTextField jFrtLiteralB;
    private javax.swing.JFormattedTextField jFrtLiteralC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblCorreo;
    private javax.swing.JLabel jLblLiteralA;
    private javax.swing.JLabel jLblLiteralB;
    private javax.swing.JLabel jLblLiteralC;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblTelefono;
    private javax.swing.JLabel jLblX1;
    private javax.swing.JLabel jLblX2;
    private java.awt.Label jLbl_anio;
    private java.awt.Label jLbl_editorial;
    private java.awt.Label jLbl_titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelDatosUsuario;
    private javax.swing.JPanel jPanel_buttons;
    private javax.swing.JPanel jPanel_prop;
    private javax.swing.JPanel jPnlFormulaGeneral;
    private javax.swing.JPanel jPnlMiFormula;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable_lectores;
    private javax.swing.JTable jTable_libros;
    private javax.swing.JTable jTable_prestamos;
    private javax.swing.JTabbedPane jTbdFormulas;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jTxtAnio;
    private javax.swing.JTextField jTxtCorreo;
    private javax.swing.JTextField jTxtEditorial;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtNombre2;
    private javax.swing.JTextField jTxtTelefono;
    private javax.swing.JTextField jTxtTitulo;
    private java.awt.TextField jTxtTitulo2;
    private javax.swing.JComboBox<String> jcmbcredencial;
    private javax.swing.JComboBox<String> jcmblibro;
    private java.awt.Label label1;
    private javax.swing.JLabel lblautor;
    private javax.swing.JLabel lblcantidad;
    private javax.swing.JLabel lblmostrar;
    private javax.swing.JTextField txtautor;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtgrupo;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

  private void cargarcombo(JComboBox c) {
    DefaultComboBoxModel combo = new DefaultComboBoxModel();
    c.setModel(combo);
    
    try {
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT titulo FROM libro");
        
        while (rs.next()) {
            String titulo = rs.getString(1);
            combo.addElement(titulo);
            System.out.println("exito");
        }
        
        rs.close();
        st.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar los datos", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
private void cargarcombo2 (JComboBox c) {
    DefaultComboBoxModel combo = new DefaultComboBoxModel();
    c.setModel(combo);
    
    try {
        // Obtener la lista de credenciales desde la base de datos
        ListaCredenciales listaCredenciales = new ListaCredenciales();
        
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT credencial FROM credenciales");
        
        while (rs.next()) {
            String nombreCredencial = rs.getString("credencial");
            Credencial credencial = new Credencial(nombreCredencial);
            listaCredenciales.agregarCredencial(credencial);
            combo.addElement(nombreCredencial);
        }
        
        rs.close();
        st.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al cargar los datos", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
 





   

}////cierra todo el programa
